name: Azure .NET Coinbase.Api 

on:
  push:
    branches: [ 'master', 'development' ]
  pull_request:
    branches: [ 'master' ]

env:
  AZURE_WEBAPP_NAME: coinbase-service
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      
      - name: Restore
        run: dotnet restore ./Coinbase.Api/Coinbase.Api
        
      - name: Build
        run: dotnet build ./Coinbase.Api/Coinbase.Api --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Coinbase.Api/Coinbase.Api --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Test Coinbase.Api.Tests
      run: dotnet test --no-build --verbosity normal
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.'
