name: Publish .NET Coinbase.Api 

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: 'coinbase-service'
  AZURE_WEBAPP_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
       
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./Coinbase.Api/Coinbase.Api
        
      - name: Build
        run: dotnet build ./Coinbase.Api/Coinbase.Api --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Coinbase.Api/Coinbase.Api --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PATH }}/${{ env.AZURE_WEBAPP_NAME}}'
        
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.AZURE_WEBAPP_NAME }}'
          package: '${{ env.AZURE_WEBAPP_PATH }}/${{ env.AZURE_WEBAPP_NAME}}'
