name: .NET Coinbase.Services.Identity Dev

on:
  workflow_dispatch:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies Coinbase.Services.Identity
      run: dotnet restore
      working-directory: ./Coinbase.Services.Identity/Coinbase.Services.Identity
      
    - name: Build Coinbase.Services.Identity
      run: dotnet build --no-restore
      working-directory: ./Coinbase.Services.Identity/Coinbase.Services.Identity
      
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Test Coinbase.Services.Identity.Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Coinbase.Services.Identity/Coinbase.Services.Identity.Tests
